import com.diffblue.cover.buildsystem.gradle.plugin.CoverPlugin
import com.diffblue.cover.buildsystem.gradle.plugin.GradleSpy

initscript {
  dependencies {
    classpath files(System.properties['com.diffblue.cover.buildsystem.gradle.model-jar'])
  }
}

allprojects {
  apply plugin: CoverPlugin
  addListener(GradleSpy.getInstance())
}

dependencies {
    compileOnly "com.diffblue.cover:cover-annotations:1.5.0"

    compileOnly "com.diffblue.cover:cover-annotations:1.5.0"

    compileOnly "com.diffblue.cover:cover-annotations:1.5.0"

    compileOnly "com.diffblue.cover:cover-annotations:1.5.0"

    compileOnly "com.diffblue.cover:cover-annotations:1.5.0"

    compileOnly "com.diffblue.cover:cover-annotations:1.5.0"

    compileOnly "com.diffblue.cover:cover-annotations:1.5.0"

    testImplementation "com.diffblue.cover:cover-annotations:1.5.0"
    testImplementation "com.diffblue.cover:cover-annotations:1.5.0"
    testImplementation "com.diffblue.cover:cover-annotations:1.5.0"
    testImplementation "com.diffblue.cover:cover-annotations:1.5.0"
    testImplementation "com.diffblue.cover:cover-annotations:1.5.0"
    testImplementation "com.diffblue.cover:cover-annotations:1.5.0"
    testImplementation "com.diffblue.cover:cover-annotations:1.5.0"
}
